Candidate and dev/nightly builds support
redhat-partner-solutions/crucible pull request #121
Opened 2022-04-05 23:10 UTC by thekad

Routinely, crucible only supports 1 "blessed" version from each major OCP branch. If you want to support release candidates and development builds, a few changes are needed.
Having these changes plus an inventory that looks something like this:

```yaml
    assisted_service_openshift_versions_defaults:
      "4.9":
        release_version: 4.9.0-0.nightly-2021-09-09-145014
        display_name: 4.9.0-0.nightly-2021-09-09-145014
        support_level: dev-preview
        release_image: "quay.io/openshift-release-dev/ocp-release-nightly@sha256:beb878e06dbe123a9711c5f832587670fc135264a452d1c6c498b84896f468a9"
        rhcos_version: 49.84.202107010027-0
        rhcos_image: "https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.9/49.84.202107010027-0/x86_64/rhcos-49.84.202107010027-0-live.x86_64.iso"
        rhcos_rootfs: "https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.9/49.84.202107010027-0/x86_64/rhcos-49.84.202107010027-0-live-rootfs.x86_64.img"
    supported_ocp_versions:
      - 4.9.0-0.nightly-2021-09-09-145014
    ocp_release_versions_map_all:
      "4.9":
        long: 4.9.0-0.nightly-2021-09-09-145014
        hash: sha256:beb878e06dbe123a9711c5f832587670fc135264a452d1c6c498b84896f468a9
        url: quay.io/openshift-release-dev/ocp-release-nightly
    openshift_full_version: 4.9.0-0.nightly-2021-09-09-145014
    release_image_remote: quay.io/openshift-release-dev/ocp-release-nightly
    release_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview
```

Allows you to test a development build.

I've tried to make it backwards compatible but I bet there are quite a few changes needed, please do review carefully and let me know any questions :smiley:

2022-04-06 09:56 UTC, nocturnalastro commented on roles/boot_iso/tasks/kvm.yml
> +    timeout: 90
Nice :)

2022-04-06 14:25 UTC, nocturnalastro commented on roles/get_image_hash/tasks/get_image_hash.yml
> +  when: not (item.value.hash | default('')) != ''
I like this. I've been meaning to cache the hashes for a while but haven't gotten round to it this makes it pretty trivial.

2022-04-06 18:13 UTC, akiselev1 commented
Can you add inventory example for a different minor version, like 4.9.1 instead of 4.9.0?

2022-04-06 22:14 UTC, thekad commented
@akiselev1 I have updated the PR description to include a more complete example.

2022-04-07 09:54 UTC, nocturnalastro approved these changes

2022-04-07 13:27 UTC, arjuhe requested changes
Looks good to me. Please squash your commits.

2022-04-07 14:00 UTC, nocturnalastro commented
@arjuhe I think the commits are fine as they are. They each contain distinct info and have good explanations in them.

2022-04-07 14:11 UTC, thekad commented
@arjuhe @nocturnalastro one thing to consider is how to handle ocp_release_versions_map_all being a dictionary now instead of a list

2022-04-07 18:19 UTC, thekad commented
> @arjuhe @nocturnalastro one thing to consider is how to handle ocp_release_versions_map_all being a more complex dictionary now



> @arjuhe @nocturnalastro one thing to consider is how to handle ocp_release_versions_map_all being a more complex dictionary now

Pushed a commit that deals with this problem, can now work with both types of version maps

2022-04-07 18:19 UTC, thekad commented
> @arjuhe @nocturnalastro one thing to consider is how to handle ocp_release_versions_map_all being a more complex dictionary now



> @arjuhe @nocturnalastro one thing to consider is how to handle ocp_release_versions_map_all being a more complex dictionary now

Pushed a commit that deals with this problem, can now work with both types of version maps

2022-04-08 08:19 UTC, nocturnalastro commented
Thanks for making it backwards compatible. For some reason I had thought it was already a dict, that's my bad. 

Thinking about this we may want to either convert `ocp_release_versions_map_all` to a list or key off of the long name/version. In V2 it is possible to give multiple Z stream releases unlike in V1. While it doesn't mean we have to it would limit the assisted installer deployed by crucible. This is not something that needs to be addressed here but something we should address in the future.

2022-04-08 08:35 UTC, nocturnalastro commented
As per your docs linked in the commit, you need the correct auth to pull from `quay.io/openshift-release-dev/ocp-release-nightly`. Is there any documentation of how to get this or is part of the every `cloud.redhat.com` `pull secret`

While at the moment this is a fairly "advanced" usage of crucible. The selection of specific versions has been cropping up a lot lately. I think adding a "`custom_version`" object which required the values needed for all the overrides might be something worth looking into. @arjuhe can you make sure that we make a jira. Sorry for the ramble

2022-04-08 19:46 UTC, thekad commented
+1 to make the versions map key off openshift_full_version, that would make things much easier and clearer, I'd toyed with a change like that but I didn't feel comfortable pushing such a breaking change, opted for the least intrusive one.
I have amended the documentation I linked with a link to get your pull-secret, and yeah every such secret gives you access to the right quay repo.
I can squash my commits no problem, just got give the word and I'll push.

2022-04-13 13:21 UTC, arjuhe approved these changes

2022-04-13 13:22 UTC, arjuhe commented
@nocturnalastro I'll start up a story for a custom version parameter.

2022-04-13 13:30 UTC, merged

2022-10-11 07:07 UTC, thekad commented
+1 to have it key off openshift_full_version that would make things
infinitely easier and clearer. I almost did that, but that would break
things in such a way I wasn't comfortable pushing on my own.

On Fri, Apr 08, 2022 at 01:20:05AM -0700, Michele Costa wrote:
> Thanks for making it backwards compatible. For some reason I had thought it was already a dict, that's my bad. 
> 
> Thinking about this we may want to either convert `ocp_release_versions_map_all` to a list or key off of the long name/version. In V2 it is possible to give multiple Z stream releases unlike in V1. While it doesn't mean we have to it would limit the assisted installer deployed by crucible. This is not something that needs to be addressed here but something we should address in the future.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/redhat-partner-solutions/crucible/pull/121#issuecomment-1092588251
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

--