Have sushy tools installed in a virtual env
redhat-partner-solutions/crucible pull request #192
Opened 2022-11-23 14:49 UTC by thekad

Currently, sushy tools is installed in the system-wide python path, this causes issues with e.g. newer versions of libraries in the sushy releases, and overwriting RPM files with PIP files. Also adjusting the systemd service file to use the virtual environment.

2022-11-23 14:49 UTC, thekad commented
cc @p3ck

2022-11-25 11:57 UTC, nocturnalastro commented
I hit this error `sushy-emulator[900973]: [2022-11-25 05:32:14,748] ERROR in main: libvirt driver not loaded` I think the python package for the libvirt bindings isn't in the virtual env

2022-11-25 12:05 UTC, nocturnalastro commented
A quick attempt at adding libvirt-python failed.

2022-11-28 14:39 UTC, thekad commented
Hmmmm, my virtualenv must've been polluted, let me make an attempt from zero and will try to figure it out

2022-11-30 22:42 UTC, thekad commented
@nocturnalastro it wasn't my virtualenv, rather my machine had libvirt-devel already installed, can you take a look please ?

2022-12-01 10:20 UTC, nocturnalastro commented on roles/setup_sushy_tools/tasks/main.yml
> +      loop: "{{ sushy_pip_packages }}"
Name can take a list no need to loop.

2022-12-01 11:07 UTC, nocturnalastro commented on roles/setup_sushy_tools/defaults/main.yml
> +  - libvirt-devel
Looks like from my test that you also need `gcc` :)

2022-12-01 11:18 UTC, nocturnalastro requested changes
After adding `gcc` my test passed sushy tool the sushy tool interactions. Once that is added and the loop is removed, it looks good to me :)

2022-12-02 17:47 UTC, nocturnalastro approved these changes
Thanks for this :) @arjuhe could you take a look at this :)

2022-12-12 14:27 UTC, arjuhe approved these changes
LGTM

2022-12-12 15:05 UTC, merged