Some clean up for VMs template
redhat-partner-solutions/crucible pull request #2
Opened 2021-09-21 00:25 UTC by nocturnalastro

2021-09-21 11:06 UTC, mkochanowski requested changes

2021-09-21 11:06 UTC, mkochanowski commented on roles/create_vms/tasks/main.yml
> +        'uuid': hostvars[item]['uuid'] | default(false),
I think a more intuitive default value would be an empty string. We should not mix different types (uuid string, boolean) for the same variable (`kvm_nodes[*]['uuid']`).

2021-09-21 13:15 UTC, crwr45 approved these changes

2021-09-23 13:57 UTC, mkochanowski approved these changes

2021-09-30 16:01 UTC, merged