Fix the check so it doesn't require uppercase hex
redhat-partner-solutions/crucible pull request #225
Opened 2023-02-27 19:23 UTC by p3ck

libvirt doesn't require the mac address to be upper case.   This changes the validation to accept both upper and lower.

2023-02-27 21:50 UTC, arjuhe requested changes

2023-02-27 21:50 UTC, arjuhe commented on roles/validate_inventory/tasks/cluster.yml
>        The mac address for node {{ item }} needs to be in linx format XX:XX:XX:XX:XX:XX
Small typo on this line `linx`.

2023-02-27 21:50 UTC, arjuhe commented on roles/validate_inventory/tasks/cluster.yml
> +      - ( hostvars[item]['mac'] | string | upper | regex_search('^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$')) is not none
👍

2023-02-27 22:04 UTC, p3ck commented on roles/validate_inventory/tasks/cluster.yml
>        The mac address for node {{ item }} needs to be in linx format XX:XX:XX:XX:XX:XX
Thanks, fixed that as well

2023-02-28 09:24 UTC, nocturnalastro approved these changes

2023-02-28 09:25 UTC, merged