Rhel9
redhat-partner-solutions/crucible pull request #293
Opened 2023-11-29 15:27 UTC by nocturnalastro

2023-11-29 16:32 UTC, novacain1 reviewed
Just a suggestion on typos here, misspellings I noticed.

2023-11-30 10:11 UTC, nocturnalastro commented
@arjuhe I opened a new PR because pushing to your branch proved a pain.

2023-12-01 13:26 UTC, arjuhe requested changes
Just a minor change and a question.

2023-12-01 13:26 UTC, arjuhe commented on roles/patch_cluster/templates/patch-install-config.j2
> +{# note: This current breaks the current assisted installer
This _currently_ breaks

2023-12-01 13:26 UTC, arjuhe commented on roles/setup_sushy_tools/tasks/main.yml
> +            (is_on_rhel9 | bool) | ternary(sushy_packages_rhel9, sushy_packages_rhel8)
Checking the spelling this time

2023-12-01 13:26 UTC, arjuhe commented on roles/validate_inventory/defaults/main.yml
> +  - 4.14.2
Do you think the "versions tested" list from the README should match the z stream list here?

2023-12-04 10:33 UTC, nocturnalastro commented
@arjuhe Could you take a look at this again :)

2023-12-04 15:50 UTC, arjuhe approved these changes
Thx LGTM

2023-12-04 16:05 UTC, merged