Configure VM host network via nmstate
redhat-partner-solutions/crucible pull request #48
Opened 2021-11-29 16:49 UTC by nocturnalastro

2021-11-30 15:47 UTC, crwr45 approved these changes

2021-11-30 19:46 UTC, arjuhe reviewed
I've been avoiding it, but I'll start this now.

2021-12-02 17:59 UTC, mkochanowski requested changes

2021-12-02 17:59 UTC, mkochanowski commented on roles/apply_nmstate/tasks/main.yml
> +- name: "Copy nmstate_yaml to {{ nmstate_config_path }}"
Would `nmstate_rendered_yaml` be a better name for `nmstate_yaml`? As far as I understand, the variable holds a rendered template for _nmstate_.

2021-12-02 17:59 UTC, mkochanowski commented on roles/setup_vm_host_network/defaults/main.yml
> +bridge_name: "{{ cluster_name }}-br"
Missing `vm_` prefix here

2021-12-02 17:59 UTC, mkochanowski commented on roles/process_nmstate/defaults/main.yml
> +target_name: "{{ inventory_hostname }}"
With `{{ inventory_hostname }}` var assignments like these, I think it'd be a great practice to leave one or two sentences explaining why that's required for each scenario. This comment could make it a little easier for the reader to understand the execution flow.

2021-12-03 13:47 UTC, mkochanowski approved these changes

2021-12-03 16:39 UTC, arjuhe approved these changes

2021-12-03 17:41 UTC, merged