add openshift-clients to bastion dependencies
redhat-partner-solutions/crucible pull request #59
Opened 2021-12-08 18:10 UTC by crwr45

It is not possible to cleanly install `kubectl` and `oc` on the bastion host given our current constraint of not requiring root on the bastion. In lieu of that, this add documentation of the requirement for them.

For an incomplete example of automating the install on the bastion, see https://github.com/redhat-partner-solutions/crucible/pull/58 which removes the `tar` install and therefore risks missing dependencies.

Signed-off-by: Charlie Wheeler-Robinson <cwheeler@redhat.com>

2021-12-08 18:15 UTC, mkochanowski approved these changes

2021-12-09 13:49 UTC, snecklifter approved these changes
LGTM

2021-12-10 14:15 UTC, arjuhe requested changes
Fix the name of RHSM and its good.

2021-12-10 14:49 UTC, arjuhe requested changes
my previous review disappeared.

2021-12-10 14:49 UTC, arjuhe commented on README.md
> +**Important Note** `openshift-clients` requires an [activation through the Red Hat Subscription Manager](https://docs.openshift.com/container-platform/4.9/cli_reference/openshift_cli/getting-started-
The official name is RHSM (Red Hat Subscription Management) https://access.redhat.com/products/red-hat-subscription-management

2021-12-10 15:12 UTC, arjuhe approved these changes

2021-12-10 15:29 UTC, merged