Support for Nokia servers (redfish), post install fetch cluster_id, u…
redhat-partner-solutions/crucible pull request #73
Opened 2022-01-25 08:42 UTC by dsimonov1

…pdated docs/inventory.md with VLAN network_config

2022-01-25 08:59 UTC, dsimonov1 commented on post_install.yml
> +    URL_ASSISTED_INSTALLER_CLUSTER: "{{ ASSISTED_INSTALLER_BASE_URL }}/clusters/{{ lookup('file', '/home/ansible/crucible/fetched/cluster.txt') }}"
This one was mistakenly hardcoded, however "{{ fetched_dest }}" can be used:
"{{ ASSISTED_INSTALLER_BASE_URL }}/clusters/{{ lookup('file', fetched_dest+'cluster.txt') }}"

2022-01-25 09:03 UTC, dsimonov1 commented on roles/boot_iso/tasks/nokia/iso_config_mount_iso.yml
> +---
This one is a fall back, not sure why, and it was not used.

2022-01-25 09:15 UTC, snecklifter requested changes

2022-01-25 09:15 UTC, snecklifter commented on roles/boot_iso/tasks/nokia/iso_config_mount_iso.yml
> +- name: Unmount SuperMicro ISO
Name needs changing here

2022-01-25 09:15 UTC, snecklifter commented on roles/boot_iso/tasks/nokia/iso_config_mount_iso.yml
> +- name: Mount SuperMicro ISO
and here

2022-01-25 09:15 UTC, snecklifter commented on docs/inventory.md
> +#### VLAN
I think it might be better to break out the nokia support, post install patch and this doc update into separate PRs as they are unrelated.

2022-01-25 09:44 UTC, snecklifter approved these changes
LGTM!

2022-01-31 10:14 UTC, nocturnalastro requested changes

2022-01-31 10:14 UTC, nocturnalastro commented on roles/boot_iso/tasks/nokia/main.yml
> +      - boot_iso_url is match("https?://.+/.+/.+")
Do the nokia servers require the same `http://domain.com/foo/bar.iso` pattern as required by the SuperMicros if not lets not enforce it.

2022-01-31 10:14 UTC, nocturnalastro commented on roles/boot_disk/tasks/nokia.yml
> +            url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Managers/1/VM1/CfgCD/Actions/IsoConfig.UnMount"
This doesn't match the fall back URL in `boot_iso`, I suggest we drop the fall back as you said it isn't used.

2022-01-31 10:14 UTC, nocturnalastro commented on roles/boot_disk/tasks/nokia.yml
> +        body: '{"Boot":{"BootSourceOverrideEnabled":"Continuous","BootSourceOverrideTarget":"Hdd"}}' # Despite what the docs say HDD is not the correct value
The comment could be confusing.

2024-03-29 15:27 UTC, arjuhe commented
Closing pull request as project is being archived.

2024-03-29 15:27 UTC, closed without merging

2024-03-29 15:28 UTC, arjuhe commented
Closing pull request as project is being archived.